src/wolff.app.src
src/wolff.appup.src
src/wolff_producer.erl

Kafka leader disconnection is quite common,
logging each and every failure at error level triggers
unnecessary concnerns.
The connection pid down logs are now at info level.
Added a new error-level log after each 10 failed attempts

fix: improve logging

---

changelog.md
src/wolff_client.erl

this is only an unnecessary error log without any business impact
since the async close call is done in a un-linked process

fix: no badarg error log when closing dead connection

---

changelog.md
rebar.config
src/wolff.app.src
src/wolff.appup.src

To support SASL/GSSAPI auth.
NOTE: kafka_protocol upgrade from 4.0.3 to 4.1.0 has no support for appup, but there is so far no such requirement.

chore: upgrade kafka_protocol from 4.0.3 to 4.1.0

---

rebar.config
src/wolff_producer.erl

1. backport fixes from later versions
2. possibility to enable sasl kerberos auth
3. fix crypto:hmac/3 for otp 24
4. add more reason code to kafka_protocol schema and fixed crashing on decoding unknown error code
example logs:
```
=ERROR REPORT==== 21-Sep-2022::21:35:18.402381 ===
test-topic-2-0: still disconnected after 10 reconnect attempts, conn=leader_not_available
=INFO REPORT==== 21-Sep-2022::21:35:20.459241 ===
test-topic-2-0: connection to partition leader is down
reason=leader_not_available
```

Upgrade kafka protocol from 2.3.6.1 to 2.3.6.4

---

changelog.md
src/wolff.app.src
src/wolff.appup.src
src/wolff_producers.erl

Port of https://github.com/kafka4beam/wolff/pull/37
If a certain producer PID is dead, `pick_next_alive` will (hopefully) return a different PID and partition number.  By binding the old PID and partition number in the pattern, it'll most certainly blow up in this case.

fix(producers): wrong bound variables in pattern (1.5)

---

changelog.md
src/wolff.app.src
src/wolff.appup.src
src/wolff_client.erl
src/wolff_producer.erl
src/wolff_producers.erl
test/wolff_tests.erl

fixes: https://github.com/kafka4beam/wolff/issues/48

fix: wolff_producers should not crash when client is killed

---

src/wolff.app.src
src/wolff.appup.src
src/wolff_client.erl

Before:
```
[{<<"xxx:9092">>,{{{kpro_req,#Ref<0.2279739190.1863843841.210504>,sasl_authenticate,0,false,[[<<0,0,0,83>>,<<0,77,68,51,84,...>>]]},timeout},[{kpro_lib,send_and_recv_raw,4,[{file,"kpro_lib.erl"},{line,70}]},{kpro_lib,send_and_recv,5,[{file,"kpro_lib.erl"},{line,81}]},{kpro_sasl,'-auth/7-fun-1-',5,[{file,"kpro_sasl.erl"},{line,63}]},{kpro_sasl,do_auth,3,[{file,"kpro_sasl.erl"},{line,85}]},{kpro_connection,init_connection,2,[{file,"kpro_connection.erl"},{line,245}]},{kpro_connection,init,4,[{file,"kpro_connection.erl"},{line,175}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}]
```
After:
```
[{<<"xxx:9092">>,connection_timed_out}]
```

fix(client): fix connection error reason translation

---

src/wolff_producers.erl

There could be a race that when caller pick producer failed due to ongoing producer restarts.
As the produce API is none blocking by design, we handle this error to set partition count to -1 and will trigger an error 
``{invalid_partition_count, -1, Partitioner}`` and expecting caller to handle this specific error with retries.

fix: return partition count -1 when unavailable.

---

changelog.md
src/wolff_client.erl
src/wolff_producer.erl
src/wolff_producers.erl
test/wolff_supervised_tests.erl

Add a `max_partitions` producer config.
This config makes it possible to limit resource utilization from client side, especially when Kafka topic is not in control.
For example, in a shared data export platform, an overprovisioned topic (e.g. 100000 partitions),
may cause client side to spawn the same number of partition workers despite the fact that the user only has 
very limited resource quota (e.g. 10 message/s).

feat: add max_partitions limit

---

changelog.md
src/wolff.app.src
src/wolff.appup.src
src/wolff_client.erl
test/wolff_tests.erl

Some environments (e.g. Azure Event Hubs) appears to have a connection rate limit.
tcpdump suggested TCP SYN packet being retransmitted before the connectivity check returned error.
This PR keeps the client's metadata connection alive (instead of immediately close after usage).
And the connectivity check returns `ok` immediately if the connection process is alive.

fix(wolff_client): keep metadata connection alive

---

src/wolff.app.src
src/wolff.appup.src
src/wolff.erl
src/wolff_producer.erl
src/wolff_producers.erl
test/wolff_tests.erl

When message_too_large is received from Kafka, the producer will:
1. If single-message is too large, drop the message, and reply error to caller, also log a `error` level message
2. For `size>=2` batches, split the batches into single-message batches, and retry, then lower the config `max_batch_bytes` to half.

Split batch and retry if message_too_large

---

README.md
src/wolff_producers.erl
test/wolff_tests.erl

roudrobin was never used, and it was implemented wrong (process dict) if needed, it should be re-implemented using an atomic

refactor: remove roundrobin partitioner

---

changelog.md
include/wolff.hrl
src/wolff.erl
src/wolff_client.erl
src/wolff_producer.erl
src/wolff_producers.erl
src/wolff_producers_sup.erl
test/wolff_dynamic_topics_tests.erl
test/wolff_supervised_tests.erl

Support dynamic topics for supervised producers.
Call `wolff:ensure_supervised_dynamic_producers(ClientId, #{group => GroupName, ...})` to start a group-producer with no topics added in advance.
And call `wolff:send2` or `wolff:send_sync2` to publish messages with topic provided as an argument.

0722 dynamic topics

---

changelog.md
src/wolff_client.erl
test/wolff_dynamic_topics_tests.erl
test/wolff_supervised_tests.erl

Otherwise, an empty list might be returned if the client doens't actually attempt to ensure the leaders if the metadata is fresh.

fix: ensure at least one leader

---

README.md
changelog.md
src/wolff.app.src
src/wolff.erl
src/wolff_producer.erl
src/wolff_producers.erl
test/wolff_dynamic_topics_tests.erl
test/wolff_tests.erl

Previously, the `wolff_producer` implementation was aggressive when trying to enqueue newly received calls,
even when `max_linger_ms` is set to non-zero because the linger was implemented at the popping end of the queue.
This change moves the linger timer to the pushing end of the queue, that is, the process will delay enqueue to allow a larger collection of concurrent calls so the write batch towards disk can be larger
This also means when `max_linger_ms` is not zero, the concurrent callers will get blocked while lingering,
For completely non-blocking API, call `cast/3` or `cast/4` instead.

feat: optimize disk buffer writes

---

changelog.md
src/wolff_pendack.erl
src/wolff_producer.erl
test/wolff_dynamic_topics_tests.erl
test/wolff_tests.erl

Prior to this change, the producer uses a map to hold pending acks under the assumption that the map values should be small.
in some complex scenarios, however, the ack callback contexts can be large terms this result in great RAM consumption when there are many to ack.
This PR optimizes RAM usage by:
1. Change the call IDs to sequential
2. Do not store a copy of the context if it's identical to the last call.

refactor: compact pending-acks

---

changelog.md
src/wolff_producers.erl
test/wolff_dynamic_topics_tests.erl

Fixes a crash like this:
Generic server <0.4455.0> terminating. Reason: {{badmap,{not_initialized,1,failed_to_fetch_metadata}},[{maps,merge,[#{},{not_initialized,1,failed_
to_fetch_metadata}],[{error_info,#{module => erl_stdlib_errors}}]},{wolff_producers,do_add_topic,2,[{file,"/mnt/code/src/emqx/0/_build/default/lib/wolff/src/wolff_producers.erl"},{line,49
9}]},{wolff_producers,handle_call,3,[{file,"/mnt/code/src/emqx/0/_build/default/lib/wolff/src/wolff_producers.erl"},{line,454}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},

Fix metdata fetch failure

---

changelog.md
src/wolff_pendack.erl
src/wolff_producer.erl
test/wolff_dynamic_topics_tests.erl
test/wolff_tests.erl

introduced in 4.0.0 (the pending-ack compaction feature), when there are a few requests sent inflight, AND the replayq buffer overflows, the overflown calls to be dropped are in the middle of the compacted call-id range, hence caused below assertion failure:
{cause => unexpected_id,max => 1728471879846415,min => 1728471879846415,got => 1728471879846430},[{wolff_pendack,take2,4,[{file,"wolff_pendack.erl"},{line,122}]},{wolff_pendack,take,2,[{f
ile,"wolff_pendack.erl"},{line,92}]},{wolff_producer,evaluate_pending_ack_funs,3,[{file,"wolff_producer.erl"},{line,755}]},{wolff_producer,handle_overflow,2,[{file,"wolff_producer.erl"},{line,957}]}
The fix is to keep two queues for pending acks instead, one for the backlog (replayq buffer), another for inflight.

Fix pending ack handling for buffer overflow drops

---

changelog.md
src/wolff_pendack.erl
src/wolff_producer.erl
test/wolff_tests.erl

Introduced in 4.0.1, the sequential ID assertion only applies to the backlog items, but not for the inflight items. Because backlog queue head can be dropped when overloaded, if the inflight is not empty, when drop happened, the next insertion to inflight will detect a gap and crash.
This commit allows the gap for inflight queue.

fix: unexpected_id crash

---

.github/workflows/ci.yml
README.md
changelog.md
docker-compose.yml
include/wolff.hrl
src/wolff.app.src
src/wolff.appup.src
src/wolff_client.erl
src/wolff_producer.erl
start-kafka.sh
test/wolff_tests.erl

Two fixes:
1. If a partition-leader connection is down before any producer process get a chance to monitor it, the reason is lost. Now the EXIT reason is kept in wolff_client state.
2. If a partition is not found in the metadata response, `wolff_client` will not crash with a `badmatch`, it keeps `partition_missing_in_metadata_response` as error reason in the state for logging purpose
Will send a followup PR to support partition-count shrinking (previously only supported increasing).

250219 receive leader connection exit reason

---

changelog.md
src/wolff_client.erl
src/wolff_producers.erl
test/wolff_supervised_tests.erl

Handle topic recreation with fewer partitions.
Previously, Wolff only handled topic alteration with more partitions, but not topic re-creation with fewer partitions.
Now deleted partition producers will be gracefully shut down once new metadata is fetched, and the buffered messages will be dropped.
NOTE: As before, topic deletion (`unknown_topic_or_partition`) does not cause all partition producers to shut down.

feat: handle topic recreation with less number of partitions

---

changelog.md
rebar.config

for crc32cer-0.1.12 performance improvements on x86
performance: arm/x86 = 1/10

fix: upgrade to kafka_protocol-4.2.3

---

.github/workflows/ci.yml
include/wolff.hrl
rebar.config
src/wolff_client.erl
src/wolff_producer.erl
src/wolff_producers.erl
test/wolff_supervised_tests.erl

`{error, Reason}` tuple was not handled by wolff_producer (only expects `{conn_down, Reason}` tuple), causing the partition-leader re-discovery timer to be expired permanently.

fix: handle metadata fetch error

---

changelog.md
rebar.config

previously, 4.2.6. this upgrade improved transient dependency crc32cer build speed and link issues

chore: upgrade to kafka_ptotocol-4.2.8

---

changelog.md
src/wolff_producer.erl
test/wolff_tests.erl

Logic is similar to message_too_large: split the batch, if a single message is still too large, drop it.

fix: handle record_list_too_large error in produce response
